package.json

Use redhat as being the publisher

fix: update the publisher to be redhat

---

package.json
yarn.lock

Remove electron dependency

---

src/extension.ts

Add provider disposable into subscriptions to be disposed on deactivation

---

src/extension.ts

Pass icon in images option when registering authentication provider

---

.github/workflows/ci.yaml
.github/workflows/pr-check.yaml
__mocks__/@podman-desktop/api.js
package.json
src/authentication-server.ts
src/authentication-service.spec.ts
src/authentication-service.ts
vitest.config.js
yarn.lock

Add unit tests

---

package.json
yarn.lock

fix: update podman desktop api to latest version

---

.github/workflows/build.yaml
.github/workflows/ci.yaml
.github/workflows/pr-check.yaml
.github/workflows/release.yaml

feat: update github workflows to allow reuse the build workflow

---

.github/workflows/build.yaml

Update build.yaml to publish CI builds as latest to ghcr.io

---

README.md

Update the reference to latest available alpha image.  Also make sure to add line before the screenshots to make sure text isn't rendered around it.

README: update image

---

Containerfile

fix: include icon.png to the image

---

Containerfile

fix: include missing www resources

---

src/extension.ts

fix: add 'Red Hat Container Registry' suggested registry w/ icon

---

src/extension.ts

fix: stop using new Buffer()

---

Containerfile

fix: add woff2 font to the image

---

src/authentication-server.ts
src/authentication-service.ts
src/extension.ts
src/podman-cli.ts

fix: format with prettier

---

src/authentication-server.ts
src/authentication-service.ts

fix: add timeout period for login to finish

---

src/extension.ts

fix: cannot find user home folder errror

---

src/extension.ts
src/podman-cli.ts

fix: create facts file in vm to support multi-arch builds

---

src/extension.spec.ts
src/extension.ts

fix: run registry config and subscription initialization after login

---

src/extension.ts

fix: remove registry.redhat.io entry using correct source

---

src/extension.ts

feat: use account label as alias for registry username

---

src/extension.ts
src/podman-cli.spec.ts
src/podman-cli.ts

fix: report stderr output to the log in case of error

---

tests/src/model/pages/sso-extension-page.ts
tests/src/sso-extension.spec.ts

Adjust to the changes done in podman-desktop extensions pages. Fixes #128

chore(tests): repo extensions tests to be aligned with podman-desktop changes

---

src/extension.spec.ts
src/extension.ts

fix: add SCA check and warning with link to activate it

---

src/extension.spec.ts
src/extension.ts
src/podman-cli.spec.ts
src/podman-cli.ts
src/subscription.ts

fix: support of activation non default podman machines

---

.eslintrc.json
.github/workflows/pr-check.yaml
package.json
src/authentication-server.ts
src/authentication-service.spec.ts
src/authentication-service.ts
src/extension.spec.ts
src/extension.ts
src/logger.ts
src/podman-cli.spec.ts
src/podman-cli.ts
src/status-bar-item.ts
src/subscription.ts
src/util.ts
tests/src/model/pages/sso-extension-page.ts
tests/src/setupFiles/extended-hooks.ts
tests/src/sso-extension.spec.ts
tests/tsconfig.json

fix: linter errors and enable all usual checks for the codebase

---

package.json
rollup.config.js
tests/src/setupFiles/extended-hooks.ts
tests/src/sso-extension.spec.ts
vitest.config.js

Separate vite migration form fixing format for development files.

fix: include dev files in format:check and format:fix scripts

---

__mocks__/@podman-desktop/api.js
src/authentication-service.spec.ts
src/extension.spec.ts
src/podman-cli.spec.ts
vitest.config.js

fix: define @podman-desktop/api mock implementation in __mocks__

---

.github/workflows/e2e-main.yaml
.github/workflows/pr-check.yaml
package.json
playwright.config.ts
pnpm-lock.yaml
tests/src/sso-extension.spec.ts

Fixes #288.
Updates the e2e tests according to latest state of `@podman-desktop/tests-playwright` where some breaking changes were made.

chore(test): update e2e test to latest tests-playwright changes

---

.extfiles
.npmrc
scripts/build.cjs

node_modules folder contains external dependencies that cannot be included due to vite limitation.
Fix #296.

fix: extension build with pnpm is missing node_modules

---

.github/workflows/sso-e2e-nightly-windows.yaml

adding image version as input parameter. Also contains missing env. vars. processing or the image versions.

fix: include processing of image verions into env. vars

---

.github/workflows/sso-e2e-nightly-windows.yaml

Includes default podman version.

fix: add default podman_version for nightly runs

---

package.json

Update version to 1.0.3 before releasing it.

fix: update version to new 1.0.3 release

---

.github/workflows/sso-e2e-nightly-windows.yaml

Should fix some instabilities.

chore: update mapt version to 0.7.3

---

package.json

Update version to 1.0.4 for bugfix release

fix: update version to 1.0.4

---

.github/workflows/sso-e2e-nightly-windows.yaml

fixing env. variable `DEFAULT_PD_REPO_OPTIONS` name.

fix: missing underscore in env. var name

---

package.json

Update patch version for next release.

fix: update version to v1.0.5

---

package.json

Update version to 1.0.6 for next release candidate.
Related to #640.

fix: update version to 1.0.6 for new release

---

.github/workflows/ci.yaml
.github/workflows/pr-check.yaml
.github/workflows/release.yaml

Update github actions to use ubuntu 24.04.

fix(github-actions): use ubuntu 24.04

---

.github/workflows/e2e-main.yaml
.github/workflows/pr-check.yaml
tests/src/sso-extension.spec.ts

chore(ci): update workflows to use podman-desktop's version of node and pnpm in e2e tests

---

package.json
pnpm-lock.yaml

chore(deps): remove electron dependency since it is not necessary

---

package.json
pnpm-lock.yaml

fix: don't use next specifier

---

package.json
pnpm-lock.yaml

fix: revert to @types/node 22.x

---

.github/workflows/sso-e2e-nightly-windows.yaml

chore(ci): exclude some regions to avoid resources not available errors
