- src/extension.ts
On Linux, Podman Desktop can talk to the Podman socket of the host and to the ones of the Linux VM.  As outlinted in #42, talking to socket of the host's Podman is currently not supported by the extension.  While logging into the container registry is perfectly fine, running subscriptio-manager is not; it requires root privileges to install and run it.  So instead of a silent error, throw a user-visible error indicating that it's currently not supported on a Linux host.
Fixes: #42
> improve machine error when running on Linux

- src/extension.ts
- src/podman-cli.ts
When signing out of the Red Hat account make sure to undo the actions of signing in:
* Logging out of `registry.redhat.io`
* Running `subscription-manager unregister` inside the podman machine
Fixes: #41
I never wrote type script before but could copy-paste the logic together.
@dgolovin @benoitf PTAL
> sign out: logout of registry and unregister sub-man

- src/authentication-service.ts
- src/extension.ts
They are should be always present to have claims used in user name rendering on Authentication settings page.
For testing with #59.
> fix: use email and id.username scopes as defaults

- src/authentication-server.ts
Fix improves loading speed of success page and resource used in it.
Fix #49.
> fix: use stream to send files back to browser

- src/podman-cli.ts
`--force` will instruct subscription-manager to implicitly unregister. A defense measure against potential bugs or a pre-registered machine for some other reason.  This way, we make sure that the account and activation keys are used that we want.
> register with `--force`

- src/extension.ts
> fix: add redhat registry logo

- src/authentication-service.ts
> fix: if username and email not available show 'email not found'

- src/extension.ts
The log out happens only after all commands failed or passed, so for example if registry access configuration failed and subscription activation still running log out will happen only when latter finished.
Subscription activation failed scenario
https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/fbcaaa61-eaf7-4002-9891-92975734ce8e
Registry configuration failed scenario
https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/a8fc2bec-f18c-4eef-8ba1-dc68a9ff766e
Fix #52.
> fix: log out from RH SSO if registry config or/and subs activation failed

- Containerfile
- package.json
- yarn.lock
note that for now package.json engine or io.podman-desktop.api.version in Containerfile are not enforced by Podman Desktop but better to update them
> chore: update to Podman Desktop API 1.9.0

- src/extension.spec.ts
- src/extension.ts
- src/podman-cli.ts
> fix: add telemetry reporting

- .gitignore
- package.json
- vitest.config.js
- yarn.lock
Fixes #109.
To test this you can run:
`yarn test` -> runs all unit and e2e tests, creates junit files if env. var. CI=true is set at `test-resources` and `tests/output`.
`yarn test:unit` -> runs unit tests only
`yarn test:e2e` -> run e2e tests only -> for verification purpose, it is enough that you can verify that unit tests are not run, e2e requires some more configuration, so failures are acceptable or see below.
In order to successfully run e2e tests, you need to:
```
git clone podman-desktop
cd podman-desktop
yarn;yarn test:e2e:build
cd ..
cd podman-desktop-redhat-account-ext
yarn
export PODMAN_DESKTOP_ARGS=/path/to/podman-desktop
yarn test:e2e
```
> chore(tests): add separate npm test target for unit and e2e test calls

- src/extension.spec.ts
- src/extension.ts
- src/podman-cli.ts
Fix #116.
Some problems does not get reported. For example on windows when trying to install subscription manager on old podman vm where there is no rpm-tree cli tool , `runInstallSubscriptionMangaer' is not going to report exception and login is shown as successful, but the subscription-managre is not installed and error is not reported.
> fix: do not ignore errors in podman cli calls

- src/extension.spec.ts
- src/extension.ts
- src/podman-cli.ts
- src/telemetry.ts
PR breaks cycle in deps introduced with shared telemetry logger instance between podman-cli and extension.
> fix: break cycle in dependencies

- README.md
Move the Installation section at the bottom of the README. The README is being displayed in the extension page of Podman Desktop where the installation is already being taken care of.
@dgolovin @benoitf @jeffmaury PTAL
> README: move Installation section

- .github/workflows/e2e-main.yaml
Adding workflow that runs e2e test suite (#76) after push to merge event and on demand. It does not replace PR check that will be added as well.
> chore(ci): add E2E test workflow

- README.md
- package.json
- yarn.lock
Prepare for 1.0.1 release build:
1. Version updated to 1.0.1
2. Version of podman-desktop/api updated to 1.10.0
3. Links to images updated to use v1.0.1 tag direct links
> fix: prep for v1.0.1 build, update version to 1.0.1 and podman-desktop/api to 1.10.0

- src/authentication-service.ts
- src/extension.ts
Fix #142 by creating authentication request asyncronously and delaying openid-client ininialization until first authentication request or token refresh.
```
VM5:62 main ↪️ Activating extension (redhat.redhat-authentication) ended in 264 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.docker) ended in 227 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.lima) ended in 101 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.registries) ended in 60 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.compose) ended in 246 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.kube-context) ended in 203 milliseconds
VM5:62 main ↪️ Activating extension (podman-desktop.kind) ended in 286 milliseconds
VM5:62 main ↪️ Activating …
```
> fix: long activation time

- .extfiles
- package.json
- scripts/build.js
- tests/src/setupFiles/extended-hooks.ts
- tests/src/sso-extension.spec.ts
- vite.config.js
- vitest.config.js
- yarn.lock
fix #65.
Switching to vite for build leads to the error below
```
Error: Algorithm "sha256"  not supported. supported values: sha1, md5, passthrough
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```
It seems vite always assumes the app is going to be running in browser and embeds polyfill for 'crypto' package which supports only digests listed in the message above.
Rollup works fine, except the build.js script is very slow because it packages node_modules folder into .cdix archive.
This PR addresses it buy using .extfiles that specifies what to package. The result is a build that works much faster - 3 vs 300 seconds.
> fix: use vite build instead of rollup

- .github/workflows/pr-check.yaml
- tests/src/sso-extension.spec.ts
Fixed #93. 
Add PR check job that build extension locally and use it when running e2e tests. Encouraging shift-left workflow.
> chore(ci): add PR check e2e linux workflow

- .github/workflows/sso-e2e-nightly-windows.yaml
> chore(ci): add nightly e2e windows workflow

- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
- playwright.config.ts
Fixes #297. Use correct glob pattern to get test artifacts.
> fix(ci): use correct glob pattern to e2e test artifacts

- .github/workflows/pr-check.yaml
- tests/src/sso-extension.spec.ts
Fixed #299.
PR check now has two e2e jobs.
> chore(ci): add e2e test job that runs against production podman desktop

- __mocks__/@podman-desktop/api.js
- package.json
- pnpm-lock.yaml
- src/podman-cli.spec.ts
- src/podman-cli.ts
Fix #44.
Requires https://github.com/containers/podman-desktop/issues/5990 to be merged and podman API package published.
> feat: remove podman CLI impl copy and use podman ext API

- .github/workflows/sso-e2e-nightly-windows.yaml
Fixed #371.
Notes: Workflow is updated in general. Also, it now does not run on nightly base, but rather on after merge of new PRs.
> chore(ci): update windows e2e tests workflow

- tests/src/sso-extension.spec.ts
PR should fix a problem with instability, which is caused by podman extension not being active (sometime we need to wait a little)
> chore: adjust timeout in e2e tests

- src/extension.spec.ts
- src/extension.ts
- src/podman-cli.spec.ts
- src/podman-cli.ts
This PR is result of verification of https://github.com/podman-desktop/podman-desktop/issues/9860 by using runOptions parameter of execPodman.
Related to #44.
> fix: call podman CLI API with connection parameter

- src/extension.ts
- tsconfig.json
- types/template.d.ts
Add png module to load icons using import statement.
Fix #618.
> fix: missing Red Hat image registry icon

- src/extension.ts
Using `RHEL Server` causing a BadRequest Error and message that `Organization does not support role provided`. Developers website is now using `RHEl Workstation` role when creating activation keys. This PR updates the code to use correct role.
Fix #636.
> fix: use `RHEl Workstation` role instead of `RHEL Server`

- .github/workflows/sso-e2e-nightly-windows.yaml
Fixes #651.
Updates the workflow. Uses latest mapt image for better stability. Uses testing-prerelease podman desktop for e2e tests. Uses podman 5.4.0.
> chore: update windows workflow for e2e tests

- .gitignore
- package.json
- pnpm-lock.yaml
- src/extension.spec.ts
- src/extension.ts
- src/rh-api/registry-authorizer-schema.json
- src/rh-api/registry-authorizer.ts
- src/rh-api/subscription-schema.json
- src/rh-api/subscription.ts
- src/rh-api/utils.ts
- src/util.ts
> fix: migrate ot openapi-typescript and openapi-fetch

- src/extension.ts
Update activation key role name to new one `Red Hat Enterprise Linux Workstation`
Fix #670.
> fix: use new role to create new  subscription activation key

- .github/workflows/sso-e2e-nightly-windows.yaml
Fixing the name of the npm target. SSO does not have `test:e2e:run` as podman-desktop does.
> fix(ci): fix name of e2e npm target

- .github/workflows/e2e-main.yaml
Fixes #737. It removes the section where we set chromium as default browser, since it is causing troubles on CI.
> chore(ci): remove setting chromium as default browser

- .github/workflows/sso-e2e-nightly-windows.yaml
Fixes: #733.
Brings a configuration of the workflow to allow running of the auth. e2e tests.
> chore(ci): run auth. e2e tests on windows

- .github/workflows/sso-e2e-nightly-windows.yaml
Removes comment from bash multiline command.
> fix: remove comment from bash multiline command as it fails

- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
The `cz.archive.ubuntu.com` mirror for CRIU is currently unavailable, causing CI failures. This commit updates the download URL to use `archive.ubuntu.com` directly, which is a more reliable and generally available mirror.
This change ensures that the Podman update process in CI environments can reliably download and install the `criu` package, preventing build failures related to unreachable repositories.
> fix(ci): Update CRIU download URL
